apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lab3
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - image: '670435616773.dkr.ecr.us-east-1.amazonaws.com/assignment2-mysql:v1.0'
        name: mysql
        env:
        - name: MYSQL_APP_PASSWORD
          value: db123
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
